module AppTestIDL {
    typedef sequence<octet> Blob;

    struct Presence {
        boolean  inRange;
        string   deviceId;
        string   deviceType;
        string   timeStamp;
    };


    struct VehicleStatus {
        boolean  engineOn;
        boolean  doorsLocked;
        float    fuelPercent;
        string   location;
        string   timeStamp;
    };


    struct HomeStatus {
        sequence<string>   deviceIds;
        sequence<string>   deviceTypes;
        sequence<float>    acTemp;
        sequence<string>  acStatus;  
        sequence<boolean>  lightOn;
        sequence<float>    lightPercent; 
        sequence<boolean>  cameraOn;
        string                 timeStamp;
    };


    struct Alert {
        string  deviceId;
        string  deviceType;
        long    alert_id;
        string  level;    
        string  description;
        string  timeStamp;
    };

    struct AlertMedia { 
        string deviceId;
        string deviceType;
        long   alert_id;
        long   media_type;
        long   total_size;
        long   chunk_seq;
        long   chunk_size;
        Blob   chunk;
    };


    struct Command {
        string  deviceId;
        string  deviceType;
        string  action;    
        float   value;           
        string  timeStamp;
    };
};